// This file is auto-generated by @hey-api/openapi-ts

import type { RJSFSchema, UiSchema } from '@rjsf/utils';
import type { CreateEmployeeDto, CreateCompanyDto, CreateProjectDto } from './types.gen';

export type CreateEmployeeDtoForm = Omit<CreateEmployeeDto, "id">;

export const CreateEmployeeDtoFormSchema: RJSFSchema = {
    name: 'CreateEmployeeDto',
    type: 'object',
    properties: {
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        middleName: {
            type: 'string'
        },
        birthDate: {
            type: 'string',
            format: 'date'
        },
        employeeType: {
            anyOf: [
                {
                    type: 'string',
                    const: 'office'
                },
                {
                    type: 'string',
                    const: 'remote'
                },
                {
                    type: 'string',
                    const: 'hybrid'
                }
            ],
            type: 'string'
        },
        active: {
            type: 'boolean'
        },
        salary: {
            type: 'number'
        },
        experienceYears: {
            type: 'integer'
        },
        departmentId: {
            type: 'string',
            format: 'uuid'
        },
        managerId: {
            type: 'string',
            format: 'uuid'
        },
        mentorIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        avatar: {
            format: 'binary'
        },
        certificates: {
            type: 'array',
            items: {
                format: 'binary'
            }
        },
        address: {
            type: 'object',
            properties: {
                country: {
                    type: 'string'
                },
                city: {
                    type: 'string'
                },
                street: {
                    type: 'string'
                },
                house: {
                    type: 'string'
                },
                postalCode: {
                    type: 'string'
                },
                districtId: {
                    type: 'string',
                    format: 'uuid'
                }
            },
            required: ['country', 'city', 'street', 'house']
        },
        passport: {
            type: 'object',
            properties: {
                series: {
                    type: 'string'
                },
                number: {
                    type: 'string'
                },
                issueDate: {
                    type: 'string',
                    format: 'date'
                },
                issuedBy: {
                    type: 'string'
                },
                scan: {
                    format: 'binary'
                },
                attachments: {
                    type: 'array',
                    items: {
                        format: 'binary'
                    }
                }
            },
            required: ['series', 'number', 'issueDate']
        },
        contactInfo: {
            type: 'object',
            properties: {
                email: {
                    type: 'string'
                },
                phone: {
                    type: 'string'
                },
                telegram: {
                    type: 'string'
                }
            },
            required: ['email', 'phone']
        },
        emergencyContacts: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    fullName: {
                        type: 'string'
                    },
                    phone: {
                        type: 'string'
                    },
                    relation: {
                        anyOf: [
                            {
                                type: 'string',
                                const: 'parent'
                            },
                            {
                                type: 'string',
                                const: 'spouse'
                            },
                            {
                                type: 'string',
                                const: 'sibling'
                            },
                            {
                                type: 'string',
                                const: 'friend'
                            }
                        ],
                        type: 'string'
                    }
                },
                required: ['fullName', 'phone']
            }
        },
        educations: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    institution: {
                        type: 'string'
                    },
                    faculty: {
                        type: 'string'
                    },
                    graduationDate: {
                        type: 'string',
                        format: 'date'
                    },
                    diplomaFile: {
                        format: 'binary'
                    }
                },
                required: ['institution', 'graduationDate']
            }
        },
        skills: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    name: {
                        type: 'string'
                    },
                    level: {
                        anyOf: [
                            {
                                type: 'string',
                                const: 'junior'
                            },
                            {
                                type: 'string',
                                const: 'middle'
                            },
                            {
                                type: 'string',
                                const: 'senior'
                            },
                            {
                                type: 'string',
                                const: 'expert'
                            }
                        ],
                        type: 'string'
                    },
                    certificateId: {
                        type: 'string',
                        format: 'uuid'
                    }
                },
                required: ['name', 'level']
            }
        },
        preferredWorkspace: {
            anyOf: [
                {
                    anyOf: [
                        {
                            type: 'string',
                            const: 'office'
                        },
                        {
                            type: 'string',
                            const: 'home'
                        },
                        {
                            type: 'string',
                            const: 'coworking'
                        }
                    ],
                    type: 'string'
                },
                {
                    type: 'string',
                    format: 'uuid'
                }
            ],
            type: 'string'
        }
    },
    required: ['firstName', 'lastName', 'birthDate', 'employeeType', 'departmentId', 'address', 'passport', 'contactInfo']
};

export const CreateEmployeeDtoFormUiSchemaBase: UiSchema = {
    birthDate: {
        'ui:widget': 'customizableDate',
        'ui:options': {
            format: 'DD.MM.YYYY'
        }
    },
    departmentId: {
        'ui:widget': 'uuidSelect',
        'ui:options': {
            uuid_select_path: 'departmentId'
        }
    },
    managerId: {
        'ui:widget': 'uuidSelect',
        'ui:options': {
            uuid_select_path: 'managerId'
        }
    },
    mentorIds: {
        'ui:widget': 'uuidSelect',
        'ui:options': {
            uuid_select_path: 'mentorIds'
        }
    },
    avatar: {
        'ui:field': 'fileUpload'
    },
    certificates: {
        'ui:field': 'fileUpload'
    },
    address: {
        districtId: {
            'ui:widget': 'uuidSelect',
            'ui:options': {
                uuid_select_path: 'address_districtId'
            }
        }
    },
    passport: {
        issueDate: {
            'ui:widget': 'customizableDate',
            'ui:options': {
                format: 'DD.MM.YYYY'
            }
        },
        scan: {
            'ui:field': 'fileUpload'
        },
        attachments: {
            'ui:field': 'fileUpload'
        }
    },
    educations: {
        items: {
            graduationDate: {
                'ui:widget': 'customizableDate',
                'ui:options': {
                    format: 'DD.MM.YYYY'
                }
            },
            diplomaFile: {
                'ui:field': 'fileUpload'
            }
        }
    },
    skills: {
        items: {
            certificateId: {
                'ui:widget': 'uuidSelect',
                'ui:options': {
                    uuid_select_path: 'skills_items_certificateId'
                }
            }
        }
    },
    preferredWorkspace: {
        anyOf: [
            {
                anyOf: [
                    {},
                    {},
                    {}
                ]
            },
            {
                'ui:widget': 'uuidSelect',
                'ui:options': {
                    uuid_select_path: 'preferredWorkspace_anyOf'
                }
            }
        ]
    }
};

export type CreateEmployeeDtoI18nType = {
    "ui:title": string;
    firstName: {
        "ui:title": string;
    };
    lastName: {
        "ui:title": string;
    };
    middleName: {
        "ui:title": string;
    };
    birthDate: {
        "ui:title": string;
    };
    employeeType: {
        "ui:title": string;
    };
    active: {
        "ui:title": string;
    };
    salary: {
        "ui:title": string;
    };
    experienceYears: {
        "ui:title": string;
    };
    departmentId: {
        "ui:title": string;
    };
    managerId: {
        "ui:title": string;
    };
    mentorIds: {
        "ui:title": string;
    };
    avatar: {
        "ui:title": string;
    };
    certificates: {
        "ui:title": string;
    };
    address: {
        "ui:title": string;
        country: {
            "ui:title": string;
        };
        city: {
            "ui:title": string;
        };
        street: {
            "ui:title": string;
        };
        house: {
            "ui:title": string;
        };
        postalCode: {
            "ui:title": string;
        };
        districtId: {
            "ui:title": string;
        };
    };
    passport: {
        "ui:title": string;
        series: {
            "ui:title": string;
        };
        number: {
            "ui:title": string;
        };
        issueDate: {
            "ui:title": string;
        };
        issuedBy: {
            "ui:title": string;
        };
        scan: {
            "ui:title": string;
        };
        attachments: {
            "ui:title": string;
        };
    };
    contactInfo: {
        "ui:title": string;
        email: {
            "ui:title": string;
        };
        phone: {
            "ui:title": string;
        };
        telegram: {
            "ui:title": string;
        };
    };
    emergencyContacts: {
        "ui:title": string;
        items: {
            fullName: {
                "ui:title": string;
            };
            phone: {
                "ui:title": string;
            };
            relation: {
                "ui:title": string;
            };
        };
    };
    educations: {
        "ui:title": string;
        items: {
            institution: {
                "ui:title": string;
            };
            faculty: {
                "ui:title": string;
            };
            graduationDate: {
                "ui:title": string;
            };
            diplomaFile: {
                "ui:title": string;
            };
        };
    };
    skills: {
        "ui:title": string;
        items: {
            name: {
                "ui:title": string;
            };
            level: {
                "ui:title": string;
            };
            certificateId: {
                "ui:title": string;
            };
        };
    };
    preferredWorkspace: {
        "ui:title": string;
    };
};

export type CreateEmployeeDtoCtx = {
    uuids: {
        departmentId: Array<{
            label: string;
            value: string;
        }>;
        managerId: Array<{
            label: string;
            value: string;
        }>;
        mentorIds: Array<{
            label: string;
            value: string;
        }>;
        address_districtId: Array<{
            label: string;
            value: string;
        }>;
        skills_items_certificateId: Array<{
            label: string;
            value: string;
        }>;
        preferredWorkspace_anyOf: Array<{
            label: string;
            value: string;
        }>;
    };
};

export type CreateCompanyDtoForm = Omit<CreateCompanyDto, "id">;

export const CreateCompanyDtoFormSchema: RJSFSchema = {
    name: 'CreateCompanyDto',
    type: 'object',
    properties: {
        companyName: {
            type: 'string'
        },
        shortName: {
            type: 'string'
        },
        registrationNumber: {
            type: 'string'
        },
        taxNumber: {
            type: 'string'
        },
        registrationDate: {
            type: 'string',
            format: 'date'
        },
        companyType: {
            anyOf: [
                {
                    type: 'string',
                    const: 'llc'
                },
                {
                    type: 'string',
                    const: 'jsc'
                },
                {
                    type: 'string',
                    const: 'sole_proprietor'
                }
            ],
            type: 'string'
        },
        logo: {
            format: 'binary'
        },
        legalAddress: {
            type: 'object',
            properties: {
                country: {
                    type: 'string'
                },
                city: {
                    type: 'string'
                },
                street: {
                    type: 'string'
                },
                house: {
                    type: 'string'
                },
                postalCode: {
                    type: 'string'
                },
                districtId: {
                    type: 'string',
                    format: 'uuid'
                }
            },
            required: ['country', 'city', 'street', 'house']
        },
        actualAddress: {
            type: 'object',
            properties: {
                country: {
                    type: 'string'
                },
                city: {
                    type: 'string'
                },
                street: {
                    type: 'string'
                },
                house: {
                    type: 'string'
                },
                postalCode: {
                    type: 'string'
                },
                districtId: {
                    type: 'string',
                    format: 'uuid'
                }
            },
            required: ['country', 'city', 'street', 'house']
        },
        representatives: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    fullName: {
                        type: 'string'
                    },
                    position: {
                        type: 'string'
                    },
                    powerOfAttorneyFile: {
                        format: 'binary'
                    },
                    allowedProjectIds: {
                        type: 'array',
                        items: {
                            type: 'string',
                            format: 'uuid'
                        }
                    }
                },
                required: ['fullName', 'powerOfAttorneyFile']
            }
        },
        responsibleEmployeeId: {
            type: 'string',
            format: 'uuid'
        },
        relatedCompanyIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    },
    required: ['companyName', 'registrationNumber', 'registrationDate', 'legalAddress', 'representatives']
};

export const CreateCompanyDtoFormUiSchemaBase: UiSchema = {
    registrationDate: {
        'ui:widget': 'customizableDate',
        'ui:options': {
            format: 'DD.MM.YYYY'
        }
    },
    logo: {
        'ui:field': 'fileUpload'
    },
    legalAddress: {
        districtId: {
            'ui:widget': 'uuidSelect',
            'ui:options': {
                uuid_select_path: 'legalAddress_districtId'
            }
        }
    },
    actualAddress: {
        districtId: {
            'ui:widget': 'uuidSelect',
            'ui:options': {
                uuid_select_path: 'actualAddress_districtId'
            }
        }
    },
    representatives: {
        items: {
            powerOfAttorneyFile: {
                'ui:field': 'fileUpload'
            },
            allowedProjectIds: {
                'ui:widget': 'uuidSelect',
                'ui:options': {
                    uuid_select_path: 'representatives_items_allowedProjectIds'
                }
            }
        }
    },
    responsibleEmployeeId: {
        'ui:widget': 'uuidSelect',
        'ui:options': {
            uuid_select_path: 'responsibleEmployeeId'
        }
    },
    relatedCompanyIds: {
        'ui:widget': 'uuidSelect',
        'ui:options': {
            uuid_select_path: 'relatedCompanyIds'
        }
    }
};

export type CreateCompanyDtoI18nType = {
    "ui:title": string;
    companyName: {
        "ui:title": string;
    };
    shortName: {
        "ui:title": string;
    };
    registrationNumber: {
        "ui:title": string;
    };
    taxNumber: {
        "ui:title": string;
    };
    registrationDate: {
        "ui:title": string;
    };
    companyType: {
        "ui:title": string;
    };
    logo: {
        "ui:title": string;
    };
    legalAddress: {
        "ui:title": string;
        country: {
            "ui:title": string;
        };
        city: {
            "ui:title": string;
        };
        street: {
            "ui:title": string;
        };
        house: {
            "ui:title": string;
        };
        postalCode: {
            "ui:title": string;
        };
        districtId: {
            "ui:title": string;
        };
    };
    actualAddress: {
        "ui:title": string;
        country: {
            "ui:title": string;
        };
        city: {
            "ui:title": string;
        };
        street: {
            "ui:title": string;
        };
        house: {
            "ui:title": string;
        };
        postalCode: {
            "ui:title": string;
        };
        districtId: {
            "ui:title": string;
        };
    };
    representatives: {
        "ui:title": string;
        items: {
            fullName: {
                "ui:title": string;
            };
            position: {
                "ui:title": string;
            };
            powerOfAttorneyFile: {
                "ui:title": string;
            };
            allowedProjectIds: {
                "ui:title": string;
            };
        };
    };
    responsibleEmployeeId: {
        "ui:title": string;
    };
    relatedCompanyIds: {
        "ui:title": string;
    };
};

export type CreateCompanyDtoCtx = {
    uuids: {
        legalAddress_districtId: Array<{
            label: string;
            value: string;
        }>;
        actualAddress_districtId: Array<{
            label: string;
            value: string;
        }>;
        representatives_items_allowedProjectIds: Array<{
            label: string;
            value: string;
        }>;
        responsibleEmployeeId: Array<{
            label: string;
            value: string;
        }>;
        relatedCompanyIds: Array<{
            label: string;
            value: string;
        }>;
    };
};

export type CreateProjectDtoForm = Omit<CreateProjectDto, "id">;

export const CreateProjectDtoFormSchema: RJSFSchema = {
    name: 'CreateProjectDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        startDate: {
            type: 'string',
            format: 'date'
        },
        endDate: {
            type: 'string',
            format: 'date'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    const: 'draft'
                },
                {
                    type: 'string',
                    const: 'active'
                },
                {
                    type: 'string',
                    const: 'archived'
                }
            ],
            type: 'string'
        },
        budget: {
            type: 'number'
        },
        ownerId: {
            type: 'string',
            format: 'uuid'
        },
        reviewerIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        teamMemberIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        coverImage: {
            format: 'binary'
        },
        documents: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    title: {
                        type: 'string'
                    },
                    description: {
                        type: 'string'
                    },
                    file: {
                        format: 'binary'
                    },
                    tagIds: {
                        type: 'array',
                        items: {
                            type: 'string',
                            format: 'uuid'
                        }
                    }
                },
                required: ['title', 'file']
            }
        },
        executionMode: {
            anyOf: [
                {
                    anyOf: [
                        {
                            type: 'string',
                            const: 'internal'
                        },
                        {
                            type: 'string',
                            const: 'outsource'
                        }
                    ],
                    type: 'string'
                },
                {
                    type: 'string',
                    format: 'uuid'
                }
            ],
            type: 'string'
        }
    },
    required: ['name', 'startDate', 'ownerId', 'companyId', 'documents']
};

export const CreateProjectDtoFormUiSchemaBase: UiSchema = {
    startDate: {
        'ui:widget': 'customizableDate',
        'ui:options': {
            format: 'DD.MM.YYYY'
        }
    },
    endDate: {
        'ui:widget': 'customizableDate',
        'ui:options': {
            format: 'DD.MM.YYYY'
        }
    },
    ownerId: {
        'ui:widget': 'uuidSelect',
        'ui:options': {
            uuid_select_path: 'ownerId'
        }
    },
    reviewerIds: {
        'ui:widget': 'uuidSelect',
        'ui:options': {
            uuid_select_path: 'reviewerIds'
        }
    },
    companyId: {
        'ui:widget': 'uuidSelect',
        'ui:options': {
            uuid_select_path: 'companyId'
        }
    },
    teamMemberIds: {
        'ui:widget': 'uuidSelect',
        'ui:options': {
            uuid_select_path: 'teamMemberIds'
        }
    },
    coverImage: {
        'ui:field': 'fileUpload'
    },
    documents: {
        items: {
            file: {
                'ui:field': 'fileUpload'
            },
            tagIds: {
                'ui:widget': 'uuidSelect',
                'ui:options': {
                    uuid_select_path: 'documents_items_tagIds'
                }
            }
        }
    },
    executionMode: {
        anyOf: [
            {
                anyOf: [
                    {},
                    {}
                ]
            },
            {
                'ui:widget': 'uuidSelect',
                'ui:options': {
                    uuid_select_path: 'executionMode_anyOf'
                }
            }
        ]
    }
};

export type CreateProjectDtoI18nType = {
    "ui:title": string;
    name: {
        "ui:title": string;
    };
    description: {
        "ui:title": string;
    };
    startDate: {
        "ui:title": string;
    };
    endDate: {
        "ui:title": string;
    };
    status: {
        "ui:title": string;
    };
    budget: {
        "ui:title": string;
    };
    ownerId: {
        "ui:title": string;
    };
    reviewerIds: {
        "ui:title": string;
    };
    companyId: {
        "ui:title": string;
    };
    teamMemberIds: {
        "ui:title": string;
    };
    coverImage: {
        "ui:title": string;
    };
    documents: {
        "ui:title": string;
        items: {
            title: {
                "ui:title": string;
            };
            description: {
                "ui:title": string;
            };
            file: {
                "ui:title": string;
            };
            tagIds: {
                "ui:title": string;
            };
        };
    };
    executionMode: {
        "ui:title": string;
    };
};

export type CreateProjectDtoCtx = {
    uuids: {
        ownerId: Array<{
            label: string;
            value: string;
        }>;
        reviewerIds: Array<{
            label: string;
            value: string;
        }>;
        companyId: Array<{
            label: string;
            value: string;
        }>;
        teamMemberIds: Array<{
            label: string;
            value: string;
        }>;
        documents_items_tagIds: Array<{
            label: string;
            value: string;
        }>;
        executionMode_anyOf: Array<{
            label: string;
            value: string;
        }>;
    };
};