// This file is auto-generated by @hey-api/openapi-ts

export type AddressDto = {
    country: string;
    city: string;
    street: string;
    house: string;
    postalCode?: string;
    /**
     * UUID справочника района
     */
    districtId?: string;
};

export type PassportDto = {
    series: string;
    number: string;
    issueDate: string;
    issuedBy?: string;
    /**
     * Один файл для проверки fileUpload
     */
    scan?: Blob | File;
    /**
     * Массив файлов для проверки "сжатия" массива binary
     */
    attachments?: Array<Blob | File>;
};

export type ContactInfoDto = {
    email: string;
    phone: string;
    telegram?: string;
};

export type EmergencyContactDto = {
    fullName: string;
    phone: string;
    relation?: 'parent' | 'spouse' | 'sibling' | 'friend';
};

export type EducationDto = {
    institution: string;
    faculty?: string;
    graduationDate: string;
    diplomaFile?: Blob | File;
};

export type SkillDto = {
    name: string;
    level: 'junior' | 'middle' | 'senior' | 'expert';
    certificateId?: string;
};

export type RepresentativeDto = {
    id: string;
    fullName: string;
    position?: string;
    powerOfAttorneyFile: Blob | File;
    /**
     * Массив UUID для проверки uuidSelect + compression
     */
    allowedProjectIds?: Array<string>;
};

export type CreateEmployeeDto = {
    /**
     * Можно исключать через excludeFields
     */
    id?: string;
    firstName: string;
    lastName: string;
    middleName?: string;
    birthDate: string;
    employeeType: 'office' | 'remote' | 'hybrid';
    active?: boolean;
    salary?: number;
    experienceYears?: number;
    departmentId: string;
    managerId?: string;
    mentorIds?: Array<string>;
    avatar?: Blob | File;
    certificates?: Array<Blob | File>;
    address: AddressDto;
    passport: PassportDto;
    contactInfo: ContactInfoDto;
    emergencyContacts?: Array<EmergencyContactDto>;
    educations?: Array<EducationDto>;
    skills?: Array<SkillDto>;
    preferredWorkspace?: ('office' | 'home' | 'coworking') | string;
};

export type CreateCompanyDto = {
    id?: string;
    companyName: string;
    shortName?: string;
    registrationNumber: string;
    taxNumber?: string;
    registrationDate: string;
    companyType?: 'llc' | 'jsc' | 'sole_proprietor';
    logo?: Blob | File;
    legalAddress: AddressDto;
    actualAddress?: AddressDto;
    representatives: Array<RepresentativeDto>;
    responsibleEmployeeId?: string;
    relatedCompanyIds?: Array<string>;
};

export type ProjectDocumentDto = {
    title: string;
    description?: string;
    file: Blob | File;
    tagIds?: Array<string>;
};

export type CreateProjectDto = {
    id?: string;
    name: string;
    description?: string;
    startDate: string;
    endDate?: string;
    status?: 'draft' | 'active' | 'archived';
    budget?: number;
    ownerId: string;
    reviewerIds?: Array<string>;
    companyId: string;
    teamMemberIds?: Array<string>;
    coverImage?: Blob | File;
    documents: Array<ProjectDocumentDto>;
    executionMode?: ('internal' | 'outsource') | string;
};

export type PostEmployeesData = {
    body: CreateEmployeeDto;
    path?: never;
    query?: never;
    url: '/employees';
};

export type PostEmployeesResponses = {
    /**
     * Employee created
     */
    200: unknown;
};

export type PostCompaniesData = {
    body: CreateCompanyDto;
    path?: never;
    query?: never;
    url: '/companies';
};

export type PostCompaniesResponses = {
    /**
     * Company created
     */
    200: unknown;
};

export type PostProjectsData = {
    body: CreateProjectDto;
    path?: never;
    query?: never;
    url: '/projects';
};

export type PostProjectsResponses = {
    /**
     * Project created
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};